# Generated by Django 3.2.5 on 2022-11-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0005_auto_20211011_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
