# Generated by Django 3.2.5 on 2022-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0008_alter_producto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Retirado', 'Retirado')], default='Borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(max_length=200),
        ),
    ]
