# Generated by Django 3.2.5 on 2022-10-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En Stock', 'En Stock'), ('Sin Stock', 'Sin Stock'), ('Sin publicar', 'Sin publicar')], default='Sin publicar', max_length=15)),
                ('producto', models.CharField(max_length=200)),
                ('precio', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/%d')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
