# Generated by Django 3.2.5 on 2022-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20221104_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('En_Stock', 'En_Stock'), ('Sin Stock', 'Sin Stock'), ('Sin publicar', 'Sin publicar')], default='Sin publicar', max_length=15),
        ),
    ]
